version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6-node
      
    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "requirements.txt" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: Install awscli
          command: sudo pip install awscli

      - run:
          name: install dependencies
          command: |
            make install
            
      - run:
          name: build
          command: |
            make html-production
            
      - run:
          name: deploy
          command: |
            bash deploy.sh
            
      - run:
          name: wipe cache
          command: |
            aws cloudfront create-invalidation --distribution-id "${CLOUDFRONT_DISTRIBUTION_ID}" --paths "/*"

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}
        
      - store_artifacts:
          path: test-reports
          destination: test-reports
